theme: jekyll-theme-midnight
exclude:              ["README.MD"]
encoding:             "utf-8"

locale                   : "en-US"
title                    : "GRTrace"
title_separator          : ""
name                     : &name "Jakub Szewczyk & Grzegorz Uriasz"
description              : &description "The General Relativity rayTracer"
site.google_analytics    : false
